site_name: 极光文档
site_author: JPush Offical
site_url: http://docs.jpush.io
site_favicon: favicon.ico
site_description: JPush, JMessage, 极光推送, 极光IM, Android Push, Android 推送, 安卓推送, iOS Push, APNs, Push Notification
copyright: Copyright 2011-2016, jiguang.cn, All Rights Reserved. <br />粤ICP备12056275号-13 深圳市和讯华谷信息技术有限公司
theme_dir: '../themes/readthedocs'

pages:

- 入门指南:
  - 'JMessage 产品简介': 'guideline/jmessage_guide.md'


- Android:
  - 'SDK 开发指南': 'client/im_sdk_android.md'
  - 'SDK 集成指南': 'client/jmessage_android_guide.md'
  - 'SDK ErrorCode 定义': 'client/im_errorcode_android.md'
  - 'SDK API Doc': 'client/javadoc.md'


- iOS:
  - 'SDK 开发指南': 'client/im_sdk_ios.md'
  - 'SDK 集成指南': 'client/jmessage_ios_guide.md'
  - 'SDK ErrorCode 定义': 'client/im_errorcode_ios.md'
  - 'SDK API Doc': 'client/iOSdoc.md'

- JS:
  - 'WEB SDK 开发指南 V2': 'client/im_sdk_js_v2.md'
  - 'WEB SDK 开发指南': 'client/im_sdk_js.md'

- REST API:
  - 'REST API': 'server/rest_api_im.md'
  - 'REST Report V2': 'server/rest_api_im_report_v2.md'
  - 'REST Report': 'server/rest_api_im_report.md'
  - 'Server ErrorCode 定义': 'client/im_errorcode_server.md'
- 高级:
  - '消息协议': 'advanced/im_message_protocol.md'
  - '业务对象': 'advanced/im_objects.md'
  - '实时消息路由': 'advanced/jmessage_callback.md'
  - '高级话题': 'advanced/jmessage_topics.md'

- 最近更新: 'updates.md'

- 资源下载: 'resources.md'

